# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BechdelTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BechdelTest
  pod 'Alamofire', '~> 5.2'
  pod 'HTMLString', '~> 5.0'

  target 'BechdelTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
